name: Integration Tests

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore 19_IntroToIntegrationTests

      - name: Build
        run: dotnet build 19_IntroToIntegrationTests --configuration Release --no-restore

      - name: Run tests
        run: dotnet test 19_IntroToIntegrationTests --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
